-- Initialize pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Table to store user specific long-term demographics from interviews
CREATE TABLE IF NOT EXISTS user_profiles (
    id SERIAL PRIMARY KEY,
    github_handle VARCHAR(255) NOT NULL,
    base_cv TEXT NOT NULL,
    extended_cv TEXT,
    demographics_json JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table to log versions of the CV generated by agents
CREATE TABLE IF NOT EXISTS cv_versions (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    version_type VARCHAR(50) NOT NULL, -- e.g., 'improved_base', 'tailored', 'cover_letter', 'job_qa', 'extended_master'
    job_description TEXT, -- for tailored variants
    raw_markdown TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table to store raw concatenated text from codeconcat
CREATE TABLE IF NOT EXISTS projects_raw_text (
    id SERIAL PRIMARY KEY,
    user_profile_id INTEGER REFERENCES user_profiles(id) ON DELETE CASCADE,
    repo_name VARCHAR(255) NOT NULL,
    raw_text TEXT NOT NULL,
    file_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table to store embeddings for chunks of project code/text
CREATE TABLE IF NOT EXISTS project_embeddings (
    id SERIAL PRIMARY KEY,
    project_id INTEGER REFERENCES projects_raw_text(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding VECTOR(384), -- Embedding dimension for Gemini 2 is 768
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
